const haddin =[
    "Belli ki meydanı boş bulunca çakallar üşüşmüşler, Bilinsin ki çakalların hükmü kurt ayağa kalkana kadardır",
    "Belli ki meydanı boş bulunca çakallar üşüşmüşler, Bilinsin ki çakalların hükmü kurt ayağa kalkana kadardır",
    "Belli ki meydanı boş bulunca çakallar üşüşmüşler, Bilinsin ki çakalların hükmü kurt ayağa kalkana kadardır",
    "Belli ki meydanı boş bulunca çakallar üşüşmüşler, Bilinsin ki çakalların hükmü kurt ayağa kalkana kadardır",
    "Sizin gibi çakallara köle olacağıma kanımıda canımıda veririm!",
    "Sizde ihanetin kör kılıncı varsa bizde de hakkın kılıncı var",
    "Tilkilerin boynuna geçen kement kurda işlemez",
    "Sakın ola bir daha karşıma çıkmayasın. Gayrı bu topraklarda devlet benim!",
    "Sakın ola bir daha karşıma çıkmayasın. Gayrı bu topraklarda devlet benim!",
    "Sakın ola bir daha karşıma çıkmayasın. Gayrı bu topraklarda devlet benim!",
    "Sakın ola bir daha karşıma çıkmayasın. Gayrı bu topraklarda devlet benim!",
"Gözümden ırak olasın, Gayrı öfkemi taşımaya dağlar dahi takat getiremez",
"Gözümden ırak olasın, Gayrı öfkemi taşımaya dağlar dahi takat getiremez",
"Gözümden ırak olasın, Gayrı öfkemi taşımaya dağlar dahi takat getiremez",
"Gözümden ırak olasın, Gayrı öfkemi taşımaya dağlar dahi takat getiremez",
"Gözümden ırak olasın, Gayrı öfkemi taşımaya dağlar dahi takat getiremez",
    "Aslan kapana girdi mi çakallar bile diş bilermiş",
    "Kimse benim vermek istemediğim birşeyi benden zorla alamaz",
    "Kimse benim vermek istemediğim birşeyi benden zorla alamaz",
    "Kimse benim vermek istemediğim birşeyi benden zorla alamaz",
    "Kimse benim vermek istemediğim birşeyi benden zorla alamaz",
    "Kimse benim vermek istemediğim birşeyi benden zorla alamaz",
    "İtlerin hükmü varsa kurdun töresi vardır",
]
module.exports=haddin